 **Pandas**

Install Pandas

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Ritu Rai\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Ritu Rai\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Ritu Rai\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Ritu Rai\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Ritu Rai\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\Ritu Rai\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

Series (1D)

In [4]:
import pandas as pd

marks = pd.Series([80,90,95,88])
print(marks)

0    80
1    90
2    95
3    88
dtype: int64

DataFrame (2D)

In [9]:
import pandas as pd

data = {
    "Name": ["Vikky", "Rahul","Aman"],
    "Age": [22, 21, 23],
    "Marks": [95, 88, 91]
}

pf = pd.DataFrame(data)

In [10]:
pf

    Name  Age  Marks
0  Vikky   22     95
1  Rahul   21     88
2   Aman   23     91

data.head(10)
data.tail(10)
data.shape
data.info()
data.columns
data.describe()
data.corr()
data.duplicated().sum()
data.isnull().sum()

In [11]:
pf.head()

    Name  Age  Marks
0  Vikky   22     95
1  Rahul   21     88
2   Aman   23     91

In [12]:
import pandas as pd

df = pd.read_csv("Titanic_Cleaned.csv")

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,SurvivalStatus
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,Not Survived
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,Survived
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Survived
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,C123,S,Mrs,Survived
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,NaN,S,Mr,Not Survived

In [15]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,SurvivalStatus
886,887,0,2,"Montvila, Rev. Juozas",M,27.0,0,0,211536,13.00,NaN,S,Rev,Not Survived
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.0,0,0,112053,30.00,B42,S,Miss,Survived
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,23.45,NaN,S,Miss,Not Survived
889,890,1,1,"Behr, Mr. Karl Howell",M,26.0,0,0,111369,30.00,C148,C,Mr,Survived
890,891,0,3,"Dooley, Mr. Patrick",M,32.0,0,0,370376,7.75,NaN,Q,Mr,Not Survived

In [16]:
df.shape

(891, 14)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     891 non-null    int64
 1   Survived        891 non-null    int64
 2   Pclass          891 non-null    int64
 3   Name            891 non-null    object
 4   Sex             891 non-null    object
 5   Age             714 non-null    float64
 6   SibSp           891 non-null    int64
 7   Parch           891 non-null    int64
 8   Ticket          891 non-null    object
 9   Fare            891 non-null    float64
 10  Cabin           204 non-null    object
 11  Embarked        889 non-null    object
 12  Title           891 non-null    object
 13  SurvivalStatus  891 non-null    object
dtypes: float64(2), int64(5), object(7)
memory usage: 97.6+ KB

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Title',
       'SurvivalStatus'],
      dtype='object')

In [19]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
df.corr()

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'